[toolchain]

[features]
seeds = false
skip-lint = false

[programs.mainnet]
pumpfun = "8TmSyC9qHq1uuS8GGLbUpr9BgeMtT6jzQ9p9eEu5YVcV"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "https://mainnet.helius-rpc.com/?api-key=e2ddfac5-ccdd-4996-974d-af84e401132c"
cluster = "https://hidden-patient-slug.solana-mainnet.quiknode.pro/d8cb6d9a7b156d44efaca020f46f9196d20bc926"
# cluster = "mainnet"
# cluster = "https://mainnet.helius-rpc.com/?api-key=d973a2d5-0d39-464d-9bc0-ed372343bd53"
# cluster = "https://red-blissful-cloud.solana-mainnet.quiknode.pro/117d6105b14e6775c5b5401a893b2819fa8c357c/"

wallet = "/root/.config/solana/cupid.json"
# wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
