[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
pumpfun = "fkS7VXcRWEAShZHZK31oQnTYmnioe7GHwRAb19RkZbu"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "https://convincing-clean-pallet.solana-mainnet.quiknode.pro/783f9fd9a8ebeb75cdd9b489fd7485a601974b42/"
cluster = "devnet"
# cluster = "https://mainnet.helius-rpc.com/?api-key=d973a2d5-0d39-464d-9bc0-ed372343bd53"

wallet = "/root/.config/solana/cupid.json"
# wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
